name: Build Shoot Game with Pygbag
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Fatma Tnani - Shooter Game
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install and Build
      run: |
            echo "Attempting to install pygbag"
            python -m pip install pygbag
            echo "Successfully installed pygbag"
            echo "Attempting to build the game"
            python -m pygbag --build $GITHUB_WORKSPACE/main.py
            echo "Successfully built the game and compiled to WebAssembly"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
    branch: gh-pages
    folder: build/web
    token: ${{ secrets.GITHUB_TOKEN }}
